"""init schema

Revision ID: 0a85fdf05a04
Revises: 
Create Date: 2026-08-05 09:26:23.410327
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a85fdf05a04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_type', sa.String(length=32), nullable=False, comment='question / knowledge / essay_policy'),
    sa.Column('item_id', sa.String(length=64), nullable=False, comment='被审核内容标识'),
    sa.Column('body', sa.Text(), nullable=False, comment='待审内容正文'),
    sa.Column('version', sa.Integer(), nullable=False, comment='内容版本'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='pending/approved/rejected/corrected'),
    sa.Column('reviewer_1', sa.String(length=64), nullable=True),
    sa.Column('reviewer_2', sa.String(length=64), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_reviews_item_id'), 'content_reviews', ['item_id'], unique=False)
    op.create_index(op.f('ix_content_reviews_item_type'), 'content_reviews', ['item_type'], unique=False)
    op.create_table('essay_prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='题目标题'),
    sa.Column('kp', sa.String(length=128), nullable=True, comment='知识点标签'),
    sa.Column('material', sa.Text(), nullable=False, comment='给定资料/材料'),
    sa.Column('requirement', sa.Text(), nullable=False, comment='作答要求'),
    sa.Column('max_score', sa.Integer(), nullable=False, comment='满分'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kp', sa.String(length=128), nullable=False, comment='知识点标签（与题目 knowledge_point 对齐）'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='片段标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='知识正文（RAG 检索对象）'),
    sa.Column('source', sa.String(length=255), nullable=False, comment='来源标注（政策出处 / 真题年份），用于合规性溯源'),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='双签校验通过'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_kp'), 'knowledge_chunks', ['kp'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False, comment='考试科目：行测 / 申论'),
    sa.Column('category', sa.String(length=64), nullable=False, comment='细分：言语 / 数量 / 判断 / 资料 / 常识 / 申论写作'),
    sa.Column('qtype', sa.String(length=16), nullable=False, comment='single / multiple / essay'),
    sa.Column('stem', sa.Text(), nullable=False, comment='题干'),
    sa.Column('difficulty', sa.Integer(), nullable=False, comment='难度 1-5'),
    sa.Column('knowledge_point', sa.String(length=128), nullable=False, comment='知识点标签（能力图谱维度）'),
    sa.Column('answer', sa.Text(), nullable=True, comment='标准答案 / 评分要点'),
    sa.Column('explanation', sa.Text(), nullable=True, comment='解析'),
    sa.Column('source', sa.String(length=255), nullable=True, comment='来源，如 2024国考地市级'),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('copyright_owner', sa.String(length=255), nullable=True, comment='版权方（台账）'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='双签校验通过（WBS 5.2）'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_category'), 'questions', ['category'], unique=False)
    op.create_index(op.f('ix_questions_knowledge_point'), 'questions', ['knowledge_point'], unique=False)
    op.create_index(op.f('ix_questions_subject'), 'questions', ['subject'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False, comment='角色：user / reviewer / admin'),
    sa.Column('province', sa.String(length=32), nullable=True, comment='报考省份'),
    sa.Column('target_exam', sa.String(length=32), nullable=False, comment='目标考试：国考 / 省考 / 事业单位'),
    sa.Column('plan', sa.String(length=32), nullable=False, comment='会员等级：free / pro / pro_year（WBS 7.1）'),
    sa.Column('plan_expires_at', sa.DateTime(), nullable=True, comment='会员到期时间（pro/pro_year 有效；free 为 NULL）'),
    sa.Column('ai_quota_used', sa.Integer(), nullable=False, comment='今日已用 AI 讲解次数'),
    sa.Column('ai_quota_date', sa.String(length=10), nullable=False, comment='配额计数所属日期 YYYY-MM-DD'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('ability_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point', sa.String(length=128), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False, comment='掌握度 0-1'),
    sa.Column('attempts', sa.Integer(), nullable=False, comment='累计作答次数'),
    sa.Column('correct', sa.Integer(), nullable=False, comment='累计答对次数'),
    sa.Column('last_practiced', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ability_profiles_knowledge_point'), 'ability_profiles', ['knowledge_point'], unique=False)
    op.create_index(op.f('ix_ability_profiles_user_id'), 'ability_profiles', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('essay_grade_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=True),
    sa.Column('essay_text', sa.Text(), nullable=False, comment='考生作答'),
    sa.Column('total', sa.Float(), nullable=False, comment='总分'),
    sa.Column('dimensions', sa.JSON(), nullable=False, comment='维度分 {立意:..,结构:..}'),
    sa.Column('needs_human_review', sa.Boolean(), nullable=False, comment='是否转人工复核'),
    sa.Column('rationale', sa.Text(), nullable=True, comment='总评'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['essay_prompts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_essay_grade_records_prompt_id'), 'essay_grade_records', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_essay_grade_records_user_id'), 'essay_grade_records', ['user_id'], unique=False)
    op.create_table('exam_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('correct_rate', sa.Float(), nullable=False),
    sa.Column('weak_points', sa.JSON(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_records_user_id'), 'exam_records', ['user_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorites_question_id'), 'favorites', ['question_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False, comment='free / pro / pro_year'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='金额（分），避免浮点误差'),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False, comment='pending / paid / refunding / refunded / failed / cancelled'),
    sa.Column('payment_method', sa.String(length=16), nullable=False, comment='sandbox / wechat / alipay / manual'),
    sa.Column('out_trade_no', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_out_trade_no'), 'orders', ['out_trade_no'], unique=True)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('question_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=8), nullable=False, comment='A / B / C / D'),
    sa.Column('content', sa.Text(), nullable=False, comment='选项内容'),
    sa.Column('is_correct', sa.Boolean(), nullable=False, comment='是否为正确项'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_options_question_id'), 'question_options', ['question_id'], unique=False)
    op.create_table('study_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False, comment='计划天数'),
    sa.Column('target', sa.String(length=64), nullable=True, comment='目标考试'),
    sa.Column('summary', sa.Text(), nullable=True, comment='计划总述'),
    sa.Column('model', sa.String(length=64), nullable=True, comment='生成所用 LLM'),
    sa.Column('offline', sa.Boolean(), nullable=False, comment='True 表示 LLM 不可用走了规则降级'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_plans_user_id'), 'study_plans', ['user_id'], unique=False)
    op.create_table('user_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected', sa.Text(), nullable=True, comment='用户选择（选项标签拼接 / essay 要点）'),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False, comment='是否已复盘/标记掌握（错题本移除依据）'),
    sa.Column('time_spent_ms', sa.Integer(), nullable=False, comment='作答耗时'),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_answers_question_id'), 'user_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_answers_user_id'), 'user_answers', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False, comment='user | assistant'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', sa.Text(), nullable=False, comment='资料来源列表 JSON'),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('offline', sa.Boolean(), nullable=False, comment='是否为离线降级回答'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('plan_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False, comment='计划第几天'),
    sa.Column('focus', sa.String(length=128), nullable=False, comment='当日主攻知识点'),
    sa.Column('summary', sa.String(length=255), nullable=False, comment='当日概述'),
    sa.Column('knowledge_points', sa.Text(), nullable=False, comment='当日知识点 JSON 数组'),
    sa.Column('kind', sa.String(length=24), nullable=False, comment='practice|review_wrong|favorite|mock|explain|read'),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True, comment='关联题目 id（用于跳转刷题）'),
    sa.Column('done', sa.Boolean(), nullable=False, comment='是否已打卡完成'),
    sa.Column('checked_at', sa.DateTime(), nullable=True, comment='打卡时间（取消则清空）'),
    sa.ForeignKeyConstraint(['plan_id'], ['study_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_tasks_plan_id'), 'plan_tasks', ['plan_id'], unique=False)
    op.create_table('refund_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False, comment='退费金额（分）'),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False, comment='pending / approved / rejected / refunded'),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('eta_arrive_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refund_requests_order_id'), 'refund_requests', ['order_id'], unique=False)
    op.create_index(op.f('ix_refund_requests_user_id'), 'refund_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refund_requests_user_id'), table_name='refund_requests')
    op.drop_index(op.f('ix_refund_requests_order_id'), table_name='refund_requests')
    op.drop_table('refund_requests')
    op.drop_index(op.f('ix_plan_tasks_plan_id'), table_name='plan_tasks')
    op.drop_table('plan_tasks')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_user_answers_user_id'), table_name='user_answers')
    op.drop_index(op.f('ix_user_answers_question_id'), table_name='user_answers')
    op.drop_table('user_answers')
    op.drop_index(op.f('ix_study_plans_user_id'), table_name='study_plans')
    op.drop_table('study_plans')
    op.drop_index(op.f('ix_question_options_question_id'), table_name='question_options')
    op.drop_table('question_options')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_out_trade_no'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_question_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_exam_records_user_id'), table_name='exam_records')
    op.drop_table('exam_records')
    op.drop_index(op.f('ix_essay_grade_records_user_id'), table_name='essay_grade_records')
    op.drop_index(op.f('ix_essay_grade_records_prompt_id'), table_name='essay_grade_records')
    op.drop_table('essay_grade_records')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_ability_profiles_user_id'), table_name='ability_profiles')
    op.drop_index(op.f('ix_ability_profiles_knowledge_point'), table_name='ability_profiles')
    op.drop_table('ability_profiles')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_questions_subject'), table_name='questions')
    op.drop_index(op.f('ix_questions_knowledge_point'), table_name='questions')
    op.drop_index(op.f('ix_questions_category'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_knowledge_chunks_kp'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_table('essay_prompts')
    op.drop_index(op.f('ix_content_reviews_item_type'), table_name='content_reviews')
    op.drop_index(op.f('ix_content_reviews_item_id'), table_name='content_reviews')
    op.drop_table('content_reviews')
    # ### end Alembic commands ###
